iconSize = {
	w = hs.settings.get('menuIconSize'),
	h = hs.settings.get('menuIconSize')
}

iconPause = hs.image.imageFromASCII([[
	.1.4.a.d.
	.........
	.........
	.........
	.........
	.........
	.2.3.b.c.
]]):setSize(iconSize)

iconPlay = hs.image.imageFromASCII([[
	.........
	.1.......
	.........
	.........
	.......3.
	.........
	.........
	.2.......
	.........
]]):setSize(iconSize)

iconMusicNote = hs.image.imageFromASCII([[
	..........b.........
	....................
	............e.......
	....................
	..................c.
	....................
	..................d.
	....................
	....................
	....................
	....................
	....................
	1............1......
	....................
	..........a.f.......
	....................
	....................
	....................
	1............1......
]], {
	{ strokeColor = { alpha = 0 }, fillColor = { white = 1 } },
	{ strokeColor = { white = 1 }, fillColor = { white = 1 }, shouldClose = false }
}):setSize(iconSize)
